spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    jpa.show-sql: true